config/routes.rb
Rails.application.routes.draw do

  get '/search',            to:'static_pages#search'
  post '/search',             to:'static_pages#searching'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/terms', to: 'static_pages#terms'
  get '/signup', to:'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:show, :create, :destroy]
  resources :comments,            only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def search
  end
  
  def searching
    if params[:search][:content] == ''
      render 'search'
    else
      @microposts = Micropost.where("content LIKE ?","%#{params[:search][:content]}%")
      render 'search'
    end
  end
  
  def terms
  end
  
end

app/views/static_pages/home.html.erb
<!DOCTYPE html>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>投稿一覧</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Instagramsへようこそ</h1>
    <h2>友達と写真や動画を共有しよう！</h2>
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>  
    <p>または</p>
    <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
    <p class='for-login'>※ログインして使用してください</p>
  </div>
<% end %>

app/views/static_pages/search.html.erb
<% provide(:title, "Search") %>

<%= form_for(:search, url:search_path) do |f| %>
  <%= f.text_field :content %>
  
  <%= f.submit "検索", class: "btn btn-primary" %>
<% end %>  
<ol class = "microposts">
  <%= render @microposts if @microposts%>
</ol>

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms") %>

<h1>利用規約</h1>
<h2>Instagramsへようこそ！</h2>

<h2>この利用規約は、Instagramsをご利用いただく際に適用されるものであり、Instagramsサービスに関する情報を提供するものです。Instagramsアカウントを作成する場合、またはInstagramをご利用になる場合は、本規約に同意していただくことになります。</h2>