config/routes.rb
Rails.application.routes.draw do

  get '/search',            to:'static_pages#search'
  post '/search',             to:'static_pages#searching'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/terms', to: 'static_pages#terms'
  get '/signup', to:'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:show, :create, :destroy]
  resources :comments,            only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to "投稿する", '#', class: "btn btn-lg btn-primary" %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse ">
  <div class="container">
    <%= link_to "Instagrams", root_path, id: "logo" %>
    <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "ホーム", root_path %></li>
      <% if logged_in? %>
          <li><%= link_to "ユーザー", users_path %></li>
          <li><%= link_to "検索", search_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
          
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", current_user %></li>
            <li><%= link_to "編集", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
            <%= link_to "ログアウト", logout_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render'layouts/shim' %>
  </head>
  <body>
    <%= render'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>